[package]
name = "spl-token-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
solana-client = "2.1"
solana-sdk = "2.1"
spl-token = "3.3"
tokio = { version = "1", features = ["full"] }

